{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stargate-stack
  annotations:
{{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
  {{- if .Values.ingress.frontendHost }}
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stargate-frontend
                port:
                  number: 80
  {{- end }}
  {{- if .Values.ingress.backendHost }}
    - host: {{ .Values.ingress.backendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stargate-backend
                port:
                  number: 3001
{{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end }}
